# ============================
# CI
# ============================
ci:
  - '.github/workflows/**'

# ============================
# Android / Native Kotlin
# ============================
android:
  - "android/**"

# ============================
# iOS / Swift / Obj-C
# ============================
ios:
  - 'ios/**'

# ============================
# React Native / JS / TS
# ============================
frontend:
  - 'src/**'
  - 'js/**'
  - '*.js'
  - '*.ts'
  - '*.tsx'
  - '*.jsx'

# ============================
# Tests / Unit / Integration
# ============================
tests:
  - 'tests/**'
  - '__tests__/**'
  - '*.spec.ts'
  - '*.test.ts'
  - '*.test.js'
  - '*.spec.js'

# ============================
# Documentation
# ============================
documentation:
  - '*.md'
  - 'README.md'
