# ============================
# CI
# ============================
ci:
  - '.github/workflows/**'

# ============================
# Android / Native Kotlin
# ============================
android:
  - 'apps/mobile/android/**'

# ============================
# React Native / JS / TS
# ============================
frontend:
  - 'apps/mobile/src/**'
  - 'apps/mobile/**/*.js'
  - 'apps/mobile/**/*.ts'
  - 'apps/mobile/**/*.tsx'
  - 'apps/mobile/**/*.jsx'

# ============================
# Tests / Unit / Integration
# ============================
tests:
  - 'apps/mobile/**/tests/**'
  - 'apps/mobile/**/__tests__/**'
  - 'apps/mobile/**/*.spec.ts'
  - 'apps/mobile/**/*.test.ts'
  - 'apps/mobile/**/*.test.js'
  - 'apps/mobile/**/*.spec.js'

# ============================
# Documentation
# ============================
documentation:
  - '*.md'
  - 'docs/**'
  - 'README.md'
