# ============================
# CI
# ============================
ci:
  - '.github/**'

# ============================
# Android / Native Kotlin
# ============================
android:
  - 'android/**'

# ============================
# React Native / TypeScript
# ============================
frontend:
  - 'src/**'
  - '*.ts'
  - '*.tsx'

# ============================
# Tests
# ============================
tests:
  - '**/__tests__/**'
  - '**/*.test.ts'

# ============================
# Documentation
# ============================
documentation:
  - '**/*.md'
