# ============================
# CI
# ============================
ci:
  - '.github/**'

# ============================
# Android / Native Kotlin
# ============================
android:
  - 'apps/mobile/android/**'

# ============================
# React Native / TypeScript
# ============================
frontend:
  - 'apps/mobile/src/**'
  - 'apps/mobile/*.ts'
  - 'apps/mobile/*.tsx'

# ============================
# Tests
# ============================
tests:
  - '**/__tests__/**'
  - '**/*.test.ts'

# ============================
# Documentation
# ============================
documentation:
  - '**/*.md'
  - 'apps/docs/**'

# ============================
# Shared Package
# ============================
shared:
  - 'packages/shared/**'
