name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - enhancement
      - feature
  patch:
    labels:
      - bug
      - fix
      - refactor
      - maintenance
      - tests
      - documentation
  default: patch
categories:
  - title: 'New Features'
    labels:
      - enhancement
      - feature
  - title: 'Bug Fixes'
    labels:
      - bug
      - fix
  - title: 'Maintenance'
    labels:
      - refactor
      - maintenance
  - title: 'Documentation'
    labels:
      - documentation
  - title: 'Tests'
    labels:
      - tests
change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes'
template: |
  ## What's new

  $CHANGES
